version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - docker login -u $DOCKER_ACCOUNT_UNAME -p $DOCKER_ACCOUNT_PASS
  build:
    commands:
      - echo Build started on `date`
      - docker build -t ${ECR_REPO_URL}:${IMAGE_TAG} .
  post_build:
    commands:
      - echo Build completed on `date`
      - aws ecr get-login-password --region $AWS_REGION | docker login --username $DOCKER_UNAME --password-stdin $DOCKER_PASS
      - docker push ${ECR_REPO_URL}:${IMAGE_TAG}
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME ${ECR_REPO_URL}:${IMAGE_TAG} > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
